name: Build

on: 
  push: 
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/        
      - run: npm install
      - run: tsc
      - run: npx c8 --reporter=lcov node ./test.mjs .
      - run: npx codecov
        env:
          CODECOV_TOKEN: ${{secrets.codecov_token}}
      - run: npm run build-css
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
